__provider.tc.0=org.sterl.llmpeon.test.EclipseWorkspaceReadFilesToolTest
__provider.tc.1=org.sterl.llmpeon.test.AbstractTest
__provider.tc.2=org.sterl.llmpeon.test.EclipseWorkspaceWriteFilesToolTest
classLoaderOrder=booterFirst
printBundles=false
printWires=false
redirectTestOutputToFile=false
reportsdirectory=/home/runner/work/eclipse-peon-ai/eclipse-peon-ai/org.sterl.llmpeon.test/target/surefire-reports
rerunFailingTestsCount=0
runOrder=filesystem
skipAfterFailureCount=0
testclassesdirectory=/home/runner/work/eclipse-peon-ai/eclipse-peon-ai/org.sterl.llmpeon.test/target/classes
testpluginname=org.sterl.llmpeon.test
testprovider=org.apache.maven.surefire.junitcore.JUnitCoreProvider
trimStackTrace=false
